version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sls-rtc-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1py08bercz75s"
s3_prefix = "sls-rtc-backend"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

