/*
 * ビデオミーティングスペース管理API
 *
 * ビデオミーティングスペース管理API https://github.com/hogehoge-banana/sls-rtc-backend
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//

	sw "github.com/hogehoge-banana/sls-rtc-backend/pkg/swagger"
	"github.com/rs/cors"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	handler := cors.Default().Handler(router)

	log.Fatal(http.ListenAndServe(":2000", handler))
}
