/*
 * ビデオミーティングスペース管理API
 *
 * ビデオミーティングスペース管理API https://github.com/hogehoge-banana/sls-rtc-backend
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// request to connect 
type PushSubscription struct {

	P256dh string `json:"p256dh"`

	Auth string `json:"auth"`

	Endpoint string `json:"endpoint"`
}
