/*
 * ビデオミーティングスペース管理API
 *
 * ビデオミーティングスペース管理API https://github.com/hogehoge-banana/sls-rtc-backend
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Participant struct {

	ParticipantID string `json:"participantID,omitempty"`

	ConnectionID string `json:"connectionID,omitempty"`

	ClientID string `json:"clientID,omitempty"`

	RoomID string `json:"roomID,omitempty"`
}
