/*
 * ビデオミーティングスペース管理API
 *
 * ビデオミーティングスペース管理API https://github.com/hogehoge-banana/sls-rtc-backend
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v1/",
		Index,
	},

	Route{
		"Connect",
		strings.ToUpper("Post"),
		"/api/v1/connect",
		Connect,
	},

	Route{
		"ConnectParticipantIdPingGet",
		strings.ToUpper("Get"),
		"/api/v1/connect/{participantId}/ping",
		ConnectParticipantIdPingGet,
	},

	Route{
		"RoomPost",
		strings.ToUpper("Post"),
		"/api/v1/room",
		RoomPost,
	},

	Route{
		"RoomRoomIdPut",
		strings.ToUpper("Put"),
		"/api/v1/room/{roomId}",
		RoomRoomIdPut,
	},
}
