/*
 * ビデオミーティングスペース管理API
 *
 * ビデオミーティングスペース管理API https://github.com/hogehoge-banana/sls-rtc-backend
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"

	"github.com/aws/aws-lambda-go/lambda"
	"github.com/awslabs/aws-lambda-go-api-proxy/httpadapter"
	sw "github.com/hogehoge-banana/sls-rtc-backend/pkg/swagger"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	lambda.Start(httpadapter.New(router).ProxyWithContext)
}
